// 3D icon registry (Microsoft Fluent Emoji 3D, MIT). `color` is the tile backdrop.
export const ICON3D = {
  moon: { src: "/icons3d/moon.png", color: "#475569" },
  home: { src: "/icons3d/home.png", color: "#FF8A3D" },
  chat: { src: "/icons3d/chat.png", color: "#2F6BFF" },
  target: { src: "/icons3d/target.png", color: "#7C5CFF" },
  briefcase: { src: "/icons3d/briefcase.png", color: "#F5B000" },
  chart: { src: "/icons3d/chart.png", color: "#19B87A" },
  gear: { src: "/icons3d/gear.png", color: "#64748B" },
  clock: { src: "/icons3d/clock.png", color: "#EF5350" },
  money: { src: "/icons3d/money.png", color: "#19B87A" },
  building: { src: "/icons3d/building.png", color: "#00A6D6" },
  calendar: { src: "/icons3d/calendar.png", color: "#FF5FA2" },
  user: { src: "/icons3d/user.png", color: "#2F6BFF" },
  memo: { src: "/icons3d/memo.png", color: "#FF5FA2" },
  search: { src: "/icons3d/search.png", color: "#7C5CFF" },
  doc: { src: "/icons3d/doc.png", color: "#00A6D6" },
  folder: { src: "/icons3d/folder.png", color: "#F5B000" },
  bell: { src: "/icons3d/bell.png", color: "#EF5350" },
  book: { src: "/icons3d/book.png", color: "#19B87A" },
  books: { src: "/icons3d/books.png", color: "#F5B000" },
  bookmark: { src: "/icons3d/bookmark.png", color: "#FF8A3D" },
  handshake: { src: "/icons3d/handshake.png", color: "#2F6BFF" },
  diary: { src: "/icons3d/diary.png", color: "#7C5CFF" },
  map: { src: "/icons3d/map.png", color: "#19B87A" },
  gift: { src: "/icons3d/gift.png", color: "#FF5FA2" },
  link: { src: "/icons3d/link.png", color: "#00A6D6" },
  news: { src: "/icons3d/news.png", color: "#64748B" },
  heart: { src: "/icons3d/heart.png", color: "#EF5350" },
  dna: { src: "/icons3d/dna.png", color: "#7C5CFF" },
  robot: { src: "/icons3d/robot.png", color: "#00A6D6" },
  grad: { src: "/icons3d/grad.png", color: "#2F6BFF" },
  star: { src: "/icons3d/star.png", color: "#F5B000" },
  card: { src: "/icons3d/card.png", color: "#FF8A3D" },
  receipt: { src: "/icons3d/receipt.png", color: "#19B87A" },
  lock: { src: "/icons3d/lock.png", color: "#64748B" },
  globe: { src: "/icons3d/globe.png", color: "#2F6BFF" },
  question: { src: "/icons3d/question.png", color: "#FF8A3D" },
  bulb: { src: "/icons3d/bulb.png", color: "#F5B000" },
  shield: { src: "/icons3d/shield.png", color: "#19B87A" },
  trophy: { src: "/icons3d/trophy.png", color: "#FF8A3D" },
  rocket: { src: "/icons3d/rocket.png", color: "#2F6BFF" },
  fire: { src: "/icons3d/fire.png", color: "#EF5350" },
  mic: { src: "/icons3d/mic.png", color: "#2F6BFF" },
  laptop: { src: "/icons3d/laptop.png", color: "#7C5CFF" },
  clipboard: { src: "/icons3d/clipboard.png", color: "#FF8A3D" },
  compass: { src: "/icons3d/compass.png", color: "#19B87A" },
  crown: { src: "/icons3d/crown.png", color: "#F5B000" },
  puzzle: { src: "/icons3d/puzzle.png", color: "#7C5CFF" },
  tools: { src: "/icons3d/tools.png", color: "#64748B" },
  megaphone: { src: "/icons3d/megaphone.png", color: "#FF5FA2" },
  bolt: { src: "/icons3d/bolt.png", color: "#F5B000" },
  sparkles: { src: "/icons3d/sparkles.png", color: "#7C5CFF" },
  email: { src: "/icons3d/email.png", color: "#2F6BFF" },
  phone: { src: "/icons3d/phone.png", color: "#00A6D6" },
  pro: { src: "/icons3d/pro.png", color: "#2F6BFF" },
  chartbar: { src: "/icons3d/chartbar.png", color: "#00A6D6" },
  pin: { src: "/icons3d/pin.png", color: "#EF5350" },
  brain: { src: "/icons3d/brain.png", color: "#FF5FA2" },
  people: { src: "/icons3d/people.png", color: "#7C5CFF" },
} as const;

export type Icon3DName = keyof typeof ICON3D;

// Eva outline icon name -> 3D icon, so nav/settings rows that carry an eva
// icon name show the 3D version.
const EVA_TO_3D: Record<string, Icon3DName> = {
  "home-outline": "home",
  "message-circle-outline": "chat",
  "message-square-outline": "chat",
  "heart-outline": "heart",
  "clipboard-outline": "clipboard",
  "mic-outline": "mic",
  "code-outline": "laptop",
  "clock-outline": "clock",
  "compass-outline": "compass",
  "book-open-outline": "books",
  "grid-outline": "puzzle",
  "file-text-outline": "doc",
  "edit-2-outline": "memo",
  "trending-up-outline": "chart",
  "bar-chart-2-outline": "chartbar",
  "star-outline": "star",
  "share-outline": "link",
  "settings-2-outline": "gear",
  "search-outline": "search",
  "pricetags-outline": "gift",
  "percent-outline": "money",
  "people-outline": "people",
  "person-outline": "user",
  "linkedin-outline": "pro",
  "layers-outline": "puzzle",
  "headphones-outline": "phone",
  "globe-outline": "globe",
  "gift-outline": "gift",
  "folder-outline": "folder",
  "flash-outline": "bolt",
  "flag-outline": "target",
  "credit-card-outline": "card",
  "calendar-outline": "calendar",
  "briefcase-outline": "briefcase",
  "award-outline": "trophy",
  "activity-outline": "fire",
  "shield-outline": "shield",
  "bell-outline": "bell",
  "building-outline": "building",
  "lock-outline": "lock",
  "bookmark-outline": "bookmark",
};

export function icon3dFromEva(name?: string): Icon3DName | undefined {
  return name ? EVA_TO_3D[name] : undefined;
}
