// Generates lib/eva-icons.generated.ts from the `eva-icons` package's raw
// outline SVGs. We only pull in the icon names this app actually uses (see
// ICONS below) rather than bundling all ~240 outline icons, to keep the
// client bundle lean. Re-run with `node scripts/generate-icons.mjs` after
// adding a new <EvaIcon name="..."/> usage that isn't in this list yet.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SVG_DIR = path.join(
  __dirname,
  "..",
  "node_modules",
  "eva-icons",
  "outline",
  "svg"
);
const OUT_FILE = path.join(__dirname, "..", "lib", "eva-icons.generated.ts");

// Every eva-icons outline name referenced anywhere in this app.
const ICONS = [
  "home-outline",
  "message-circle-outline",
  "mic-outline",
  "clipboard-outline",
  "code-outline",
  "briefcase-outline",
  "compass-outline",
  "award-outline",
  "people-outline",
  "search-outline",
  "trending-up-outline",
  "file-text-outline",
  "edit-2-outline",
  "linkedin-outline",
  "layers-outline",
  "book-open-outline",
  "bell-outline",
  "gift-outline",
  "credit-card-outline",
  "settings-2-outline",
  "headphones-outline",
  "globe-2-outline",
  "moon-outline",
  "sun-outline",
  "log-out-outline",
  "log-in-outline",
  "person-outline",
  "person-add-outline",
  "menu-outline",
  "menu-2-outline",
  "close-outline",
  "chevron-down-outline",
  "chevron-right-outline",
  "chevron-left-outline",
  "chevron-up-outline",
  "checkmark-circle-2-outline",
  "checkmark-outline",
  "checkmark-circle-outline",
  "arrow-forward-outline",
  "arrow-right-outline",
  "arrow-circle-right-outline",
  "external-link-outline",
  "star-outline",
  "shield-outline",
  "lock-outline",
  "email-outline",
  "eye-outline",
  "eye-off-outline",
  "alert-circle-outline",
  "info-outline",
  "plus-outline",
  "plus-circle-outline",
  "close-circle-outline",
  "google-outline",
  "flash-outline",
  "activity-outline",
  "calendar-outline",
  "pricetags-outline",
  "bar-chart-2-outline",
  "corner-up-right-outline",
  "question-mark-circle-outline",
  "diagonal-arrow-right-up-outline",
  "clock-outline",
  "trash-2-outline",
  "video-outline",
  "camera-outline",
  "message-square-outline",
  "grid-outline",
  "pie-chart-outline",
  "heart-outline",
  "bulb-outline",
  "phone-call-outline",
  "share-outline",
  "upload-outline",
  "download-outline",
  "cloud-upload-outline",
  "globe-outline",
  "flag-outline",
];

function extractInner(svg) {
  const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
  if (!match) throw new Error("Could not parse svg");
  return match[1].trim();
}

const entries = ICONS.map((name) => {
  const file = path.join(SVG_DIR, `${name}.svg`);
  const raw = readFileSync(file, "utf8");
  const inner = extractInner(raw);
  return `  "${name}": \`${inner.replace(/`/g, "\\`")}\`,`;
}).join("\n");

const banner = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Source: node_modules/eva-icons/outline/svg/*.svg (Eva Icons, MIT license).
// Regenerate after adding a new EvaIcon name to the ICONS list in that script.
`;

const out = `${banner}\nexport const evaIconPaths: Record<string, string> = {\n${entries}\n};\n`;

writeFileSync(OUT_FILE, out, "utf8");
console.log(`Wrote ${ICONS.length} icons to ${path.relative(process.cwd(), OUT_FILE)}`);
